### ISSUE TITLE
Are there any instructions on how to use this?

### ISSUE THREAD

**Issue by blamoo** [jkent/Pollux-U-Boot#1]
I'm trying to install Linux on one of those nc600w thin clients and this repository is the most relevant resource I could find on this, even though the repository has been inactive for 13 years... 

Is it possible to provide some guidance on how to compile and install an alternative bootloader/OS for this device?

**Comment by jkent** [comment]
Hi blamoo,

First, have you checked what chip is in your NC600?  There were a few variants with different chips.

All of my documentation on the NC600 was lost to a server hard drive failure, unfortunately.  You'll find more resources [here](https://elinux.org/Pollux). The Pollux VR3520F is the same chip as the LF1000.  The biggest hurdle you'll face is flashing the NAND.  You're also going to need some soldering skills so you can put the device in UART boot mode.  You're going to want to use Emerald boot, instead of this repository, since I don't think I completed this U-Boot port.  Keep in mind, everything is going to be really old.

**Comment by blamoo** [comment]
It has the same IC (VR3520F) and it's already populated with a 3-pin header that gives access the stock bootloader through serial:

![serial](https://github.com/user-attachments/assets/18683590-db76-4cb5-a770-602c00abd4f4)

```
gNAND_MemBase is 0xb0c00000
gNAND_IOBase is 0xb0015874

FlashID : [0xEC] [0x76] [0x5A] [0x3F] 
FMD_Init() : 1 flash chip(s) detected
FMD_Init() : chip[0] is reset
FMD_Init() : Existing mutex [0x8725941]
OEMDebugInit -> BOARD_Initialize 

Microsoft Windows CE Ethernet Bootloader Common Library Version 1.1 Built Oct 20 2010 01:05:16
INFO:OALLogSetZones: g_oalLogMask: 0x8000000f
++ OEMPlatformInit.0
FMD_Init() : Existing mutex [0x8725941]
+ReadBootConfig

MES Boot Loader Configuration

IP: 192.168.0.18, Subnet mask: 255.255.255.0
Ether MAC address: 0:0:0:0:4D:33, DHCP: Disabled
Write to NAND: Enabled, Reserved Image Area: 40 MB
Auto Boot: NAND, OS Image will be Brought From Nand

Press [ENTER] to download now or [SPACE] to cancel.

Initiating image download in 1 seconds. 


MES Boot Loader Configuration

IP: 192.168.0.18, Subnet mask: 255.255.255.0
Ether MAC address: 0:0:0:0:4D:33, DHCP: Disabled
Write to NAND: Enabled, Reserved Image Area: 40 MB
Auto Boot: NAND, Boot delay time: 1 seconds

1) Ethernet Set
2) Boot Config
3) Image Update(USB and Serial)
4) Run Nand OS Image
5) H/W Test program down
6) data down
S) Save Config Data
D) Boot From NAND

Enter your selection: 3, 0x00000033

2) mboot Update
3) Boot Logo Update
4) OS Update
5) Format Nand (User data only)
6) Change Update Device(USB)
F) Low-level format Nand
esc) Back

Enter your selection: 
```
I'm trying to find the parts to glue together and make it work, but I have no experience with this kind of task. I'll end up having to beg for help here and there, and the fact that the hardware is over 14 years old doesn't help.

The company I work for has a bunch of these thin clients gathering dust in a warehouse, so I'm trying to give them one last use so they end up in the landfill.

**Comment by jkent** [comment]
I never figured out how mboot worked.  I didn't get a good Windows CE NAND dump before wiping mine out by accident, so that is uncharted territory.  This is why I say you need to do a little modification to the board.  With Pollux being a 533 MHz ARM926EJs, I don't see it being feasible to get them working. The display hardware will need to have VGA timing(s) added to the kernel, and you don't want anything higher than 1024x768 due to horrible AHB bus contention.  The USB is USB1.1, with a 4-port USB hub on the board, with the WIFI version using one of the available USB ports.

I've never had a kernel working on this device, most kernel work was done on the Didj.  We could dump the NAND on one of the devices so we can return them to stock condition.  Then mboot could be figured out.  How many devices do you have?

**Comment by blamoo** [comment]
It is weaker and consumes more power than a Raspberry Pi Zero ( around 300mA idle). Perhaps the most interesting thing about it is the fact that it has a built-in ethernet interface.

I have to admit that the board is quite limited and I don't have high expectations for it. Maybe it would be suitable for a headless server for some kind of automation, but overall this is more of a fun project for me.

>  How many devices do you have?

I found at least six of them in the warehouse.
